### ISSUE TITLE
example doesn't work on Android

### ISSUE THREAD

**Issue by sweetcharity** [alwx/react-native-photo-view#10]
<img width="435" alt="screenshot 2016-08-05 13 41 51" src="https://cloud.githubusercontent.com/assets/17747019/17434397/b8a06afa-5af9-11e6-89c1-11f4e7c2d2a7.png">
but works on iOS.

Android 6, Genymotion

**Comment by sweetcharity** [comment]
after manual linking red border disappeared, but photo doesn't rendered anyway. in chrome  console I have: {"source":{"uri":"https://facebook.github.io/react/img/logo_og.png"},"minimumZoomScale":0.5,"maximumZoomScale":3,"androidScaleType":"center","style":{"width":300,"height":300},"shouldNotifyLoadEvents":true,"src":"https://facebook.github.io/react/img/logo_og.png","loadingIndicatorSrc":null}


PhotoView.android.js:62

**Comment by sweetcharity** [comment]
sorry, it all works after manual linking

**Comment by zsajjad** [comment]
Manual linking means?

**Comment by Grivel-l** [comment]
I think he means manual installation, I did it and it worked
