### ISSUE TITLE
is ios pinch to zoom function not working ?

### ISSUE THREAD

**Issue by weixingsun** [alwx/react-native-photo-view#11]
Hi there, thanks for providing this great module firstly. it is working on my android devices.
when I try on my ios 9.3, I found it is not zooming at all. 
How can I zoom in fullscreen mode ? what is the trick for ios ?

Here is my code: 
                <PhotoView
                  source={{uri: uri}}
                  minimumZoomScale={0.5}
                  maximumZoomScale={3}
                  androidScaleType="center"
                  onTap={this.closeZoom}
                  style={{width: DEVICE_WIDTH, height: DEVICE_HEIGHT}}
                />

**Comment by weixingsun** [comment]
@alwx have you experienced any uncomfortable when zooming in iOS ? 
My env is RN.29, ios 9.3.3, 
My code:
            <ScrollView
                contentContainerStyle={{ alignItems:'center', justifyContent:'center'}}
                maximumZoomScale={this.props.maximumZoomScale}
                minimumZoomScale={this.props.minimumZoomScale}
                scrollEnabled={true}
                centerContent={true}
                onResponderRelease = {onResponderReleaseHandler}
            >
                <TouchableOpacity onPress={this.props.onTap?this.props.onTap:function(){}}>
                    <Image {...this.props}/>
                </TouchableOpacity>
            </ScrollView>
the only working cases are: using 3 fingers or 4 fingers on the screen. (and it is very very hard to make it zoom)
can you zoom the image by using just 2 fingers?

**Comment by alwx** [comment]
@weixingsun everything worked fine for me, but I will test and verify it today one more time.

**Comment by musicode** [comment]
is `onTap` and `onViewTap` working on iOS?

**Comment by alwx** [comment]
@musicode unfortunately, no. Both methods will be available on iOS later.
Btw, sorry for the late answer — was a bit busy during the week.

**Comment by alwx** [comment]
@musicode `onTap()` now works on iOS, `onViewTap()`, unfortunately, is still available only for Android.
