### ISSUE TITLE
Image doesn't rescale when you change orientation

### ISSUE THREAD

**Issue by narodejesus** [alwx/react-native-photo-view#117]
The image doesn't rescale if you change the orientation in IOS 
in android works perfectly

here is the screenshot
<img width="668" alt="screen shot 2017-10-05 at 3 52 22 pm" src="https://user-images.githubusercontent.com/2985439/31216183-4a3245de-a9e5-11e7-85cd-2e20a76e0da9.png">
<img width="372" alt="screen shot 2017-10-05 at 3 52 28 pm" src="https://user-images.githubusercontent.com/2985439/31216184-4b0da200-a9e5-11e7-8d3f-98eb34894d31.png">

**Comment by computerjazz** [comment]
The PhotoVIew doesn't seem to respect new width and height on orientation change.  My workaround is to set a key on the PhotoView to force a rerender on orientation change:

```javascript
            <PhotoView
                  key={`PhotoView-landscape-${isLandscape}`}
                    source={{uri: image}}
                    minimumZoomScale={1}
                    maximumZoomScale={10}
                    androidScaleType="fitCenter"
                    onLoad={() => console.log("Image loaded!")}
                    style={{ width: isLandscape ? deviceHeight : deviceWidth }}
                  />
```

**Comment by narodejesus** [comment]
thanks @computerjazz .. it works though it result some minor flickers
