### ISSUE TITLE
onLoad stops it from working

### ISSUE THREAD

**Issue by nielsswinkels** [alwx/react-native-photo-view#12]
When I have the line `onLoad={() => console.log("Image loaded!")}` in my photoview (taken from the readme example) it does not respond to pinching anymore, when I remove the line it works. I do see the message in the console, and no error message in the chrome debugger. 

I have to admit I've only tested this on android, and not in an empty app. Because I do not need the function at this point I will just remove the line and carry on, but I thought reporting it as an issue.

**Comment by alwx** [comment]
@nielsswinkels strange bug, thanks for submitting it. Unfrotunately, I was busy during the previous week and had no time to fix it, but will try to find time during the weekend.

**Comment by alwx** [comment]
Should work now (please, check, 1.2.0)
