### ISSUE TITLE
Cropper with photoView ?

### ISSUE THREAD

**Issue by ershubhamgarg** [alwx/react-native-photo-view#126]
@alwx 
Can we implement image cropper with PhotoView ?

**Comment by computerjazz** [comment]
I'm wrapping PhotoView in https://github.com/gre/react-native-view-shot and it's working well.

**Comment by tommynordli** [comment]
I would also love cropping functionality! 'react-native-view-shot' only captures the screen, so the photo quality/size will vary between devices

**Comment by tommynordli** [comment]
@ershubhamgarg did you find a good solution? Since you closed the issue.
