### ISSUE TITLE
[IOS] onScale Response SyntheticEvent

### ISSUE THREAD

**Issue by ludescher** [alwx/react-native-photo-view#178]
Im need to relocate some elements within the PhotoView[IOS] on the onScale event. Therefore i need to update the location with the help of onScale and its callback.

My issue is, Im receiving a SyntheticEvent from the onScale event, which is nullified.
Is it possible to retrive any kind of data from onScale?

**Comment by ale-diez** [comment]
For anyone wondering, the values are accessible such as 

```ts
onScale={(event) => event.nativeEvent}
```

Leaving it there since the documentation isn't very explicative and the typings are wrong
