### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by phsumi** [alwx/react-native-photo-view#184]
There's obvious issues with the Android setup, which needs to be updated, and PRs from others in the queue. Is this still maintained?

Thanks for the clarification!

**Comment by phsumi** [comment]
I only saw the issues mentioned here and in the pending PRs, but didn't install it.
I saw the `react-native-photo-view-ex` in the forks which seems to be more actively maintained, and ran this one successfully 👍

**Comment by alwx** [comment]
Yes, unfortunately, I don't have time to maintain it right now, but I plan to merge the PRs and fix the existing issues in the nearest future (probably in a week or something).
