### ISSUE TITLE
react-native-photo-view:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by chinesedfan** [alwx/react-native-photo-view#189]
I solved this problem by removing those annotations, see https://github.com/chinesedfan/react-native-photo-view/commit/f6527be033006a3a69da39cb221cf80bd0c4c9e4. Because they only help the compiler find errors.

If someone has a better way, please tell me. And sorry for the untranslated outputs.

```
> Task :react-native-photo-view:compileDebugJavaWithJavac FAILED
/Users/zhong/Desktop/github/git-point/node_modules/react-native-photo-view/android/src/main/java/com/reactnative/photoview/ImageEvent.java:12: 错误: 程序包android.support.annotation不存在
import android.support.annotation.IntDef;
                                 ^
/Users/zhong/Desktop/github/git-point/node_modules/react-native-photo-view/android/src/main/java/com/reactnative/photoview/ImageEvent.java:21: 错误: 找不到符号
  @IntDef({ON_ERROR, ON_LOAD, ON_LOAD_END, ON_LOAD_START, ON_TAP, ON_VIEW_TAP, ON_SCALE})
   ^
  符号:   类 IntDef
  位置: 类 ImageEvent
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
2 个错误
```

**Comment by chinesedfan** [comment]
Seems it is due to AndroidX, https://github.com/gitpoint/git-point/commit/017d2e5ff11e5dd5a739f589460e63c28a7c4f9a.

**Comment by stevenleeg** [comment]
Hey, I'm also seeing this issue while trying to build an `.apk` but commenting out both lines in `gradle.properties` doesn't seem to be working. Do you have any other suggestions for what might be causing this?

**Comment by stevenleeg** [comment]
Ooh, just reread this a bit later after seeing another instance of this:

```
> Task :react-native-photo-view:compileReleaseJavaWithJavac FAILED

[project-path]/app/node_modules/react-native-photo-view/android/src/main/java/com/reactnative/photoview/ImageEvent.java:12: error: package
android.support.annotation does not exist
import android.support.annotation.IntDef;
```

and managed to fix it by making the same changes that you did, but lazily doing so within `node_modules/react-native-photo-view`.

**Comment by kading** [comment]
Please see details here:
https://github.com/facebook/react-native/issues/25483#issuecomment-508446776

In short: run `npx jetify` to fix the issue (https://github.com/mikehardy/jetifier)
