### ISSUE TITLE
Could you provide an example?

### ISSUE THREAD

**Issue by flyingzl** [alwx/react-native-photo-view#2]
No example provided..And your sample codes have errors.

**Comment by alwx** [comment]
@flyingzl thanks for your report.
What errors? Isn't this example good enough?
```<PhotoView
  source={{
    uri: "http://c1.staticflickr.com/8/7412/27488731000_96ad0b9740_k.jpg"
  }}>
  minimumZoomScale={0.5}
  maximumZoomScale={3}
  androidScaleType="center"
  onLoad={() => console.log("Image loaded!")}
</PhotoView>```

**Comment by ufon** [comment]
please give a full example, because on android 0 console logs and i didnt see image. use 1.0.1 ustead 1.0.0

**Comment by alwx** [comment]
@ufon @szlezak @flyingzl I've added an example (check /example dir) and also fixed typo. Thanks for your patience.
