### ISSUE TITLE
Failed build for Android

### ISSUE THREAD

**Issue by fabiocomics** [alwx/react-native-photo-view#207]
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find me.relex:photodraweeview:1.0.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/me/relex/photodraweeview/1.0.0/photodraweeview-1.0.0.pom

**Comment by ennbou** [comment]
Try to change version number in [this gradle file](https://github.com/alwx/react-native-photo-view/blob/master/android/build.gradle#L38) and rebuild your project.

```
Path : node_modules/react-native-photo-view/android/build.gradle
```

Old
```
implementation 'me.relex:photodraweeview:1.1.3'
```

New
```
implementation 'me.relex:photodraweeview:2.1.0'
```

You can get the last version from this [link](https://mvnrepository.com/artifact/me.relex/photodraweeview/2.1.0).

Good Luck 👍 .

**Comment by fabiocomics** [comment]
Thanks! This solved my build problem.

**Comment by bogas04** [comment]
@ennbou How would we solve this in production as it requires patching the dependency?

**Comment by ennbou** [comment]
Hello @bogas04, yes you have to update it and do rebuild, the easiest way is to use a branch from PRs who they haven't merged yet, you can use this :
```json
"react-native-photo-view": "https://github.com/thanhcuong1990/react-native-photo-view.git",
```
