### ISSUE TITLE
I used with react-native-swiper on android and get app crash

### ISSUE THREAD

**Issue by MingYe-dz** [alwx/react-native-photo-view#26]

**Comment by manjeet-dobble** [comment]
same error for me on android less then 5.0

**Comment by panta82** [comment]
`react-native-swiper` + `react-native-photo-view` produce a crash on Android.

Repro steps:
1. Zoom out as far as you can
2. Let go
3. While image is resizing back, swipe left or right

**Comment by shukerullah** [comment]
To overcome this issue, I have replaced **ViewPagerAndroid** with **ViewPagerZoom** ([`react-native-image-zoom`](https://github.com/Anthonyzou/react-native-image-zoom)) in `react-native-swiper`.

**Comment by MingYe-dz** [comment]
yes，i solved it in the same way.
