### ISSUE TITLE
Doesnot work.

### ISSUE THREAD

**Issue by susylPearl** [alwx/react-native-photo-view#3]
I have set up correctly , but doesnot perform any task. whats my problem is?
Link to my file is:
https://gist.github.com/susylPearl/1ea70bcdff41e3f4bfaf0fca20ea2ecd

**Comment by JuanbingTeam** [comment]
Can see the image,but can not zoom , right?

**Comment by susylPearl** [comment]
yes, yes you are absolutely right. :)

**Comment by JuanbingTeam** [comment]
Same problem, i am digging into [PhotoDraweeView](https://github.com/ongakuer/PhotoDraweeView) .

**Comment by alwx** [comment]
@susylPearl @JuanbingTeam please, provide several details. How do you use it? Can you please share the sample of code on gist.github.com?

**Comment by JuanbingTeam** [comment]
@alwx @susylPearl 

At last, i found the problem.

The root cause is ,for the image which load from uri,  onFinalImageSet callback (PhotoView.java Line 147) will never be called.  I am still digging into this....


Here is how i use it. 

`<PhotoView source={{uri: this.props.image.url}}
          minimumZoomScale={0.5}
          maximumZoomScale={3}
          androidScaleType="center"
          onLoad={() => console.log('Image loaded')}
          style={{width: 100, height: 100}}
        />
`

**Comment by JuanbingTeam** [comment]
Solved, 

@alwx @susylPearl  I submit a pull request, please review then approve....

@alwx this project is small and useful, nice work

**Comment by susylPearl** [comment]
yes finally it works, but i got another problem, when i pinch it application get crashed. Do you also feels the same? whats the problem is?

**Comment by JuanbingTeam** [comment]
No....no crash on my two test machines.... 
You can check the error message in android monitor view.

**Comment by susylPearl** [comment]
ava.lang.ArrayIndexOutOfBoundsException: length=1; index=1
                                                                             at android.support.v4.widget.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1014)
                                                                             at android.support.v4.widget.DrawerLayout.onInterceptTouchEvent(DrawerLayout.java:1282)
                                                                             at com.facebook.react.views.drawer.ReactDrawerLayout.onInterceptTouchEvent(ReactDrawerLayout.java:37)

**Comment by susylPearl** [comment]
i have inserted photoview inside viewpager.

**Comment by JuanbingTeam** [comment]
hmmm..... never tried view pager for now. U can check whether your view pager data source is valid in debug mode...

**Comment by susylPearl** [comment]
Without viewpager also you can try pinching as much as possible.your app
will get crashed. I have tried it without viewpager.

**Comment by alwx** [comment]
@susylPearl I believe it is more like a ViewPager issue. Which ViewPager do you use? I tested it with default ScrollView (pagingEnabled = true) and everything works fine in this case.

I will close the bug.

**Comment by susylPearl** [comment]
I think you should fixed this error for betterment of your library.

**Comment by alwx** [comment]
@susylPearl The problem described in this task is already fixed. There is a separate task for your ViewPager problem
