### ISSUE TITLE
Image source bigger than screen

### ISSUE THREAD

**Issue by yachaka** [alwx/react-native-photo-view#30]
Hello,

On Android, using react-native 0.37. The pacage works great but I'm trying to display an image that is bigger than the screen. I want to resize the image for it to fit, so I can zoom/dezoom on the whole image ; now, we can only zoom on a part of the image.

I set `display: flex` on `PhotoView`, but I want to set `width: SCREEN_WIDTH` on the Image behind.

**Comment by Crash--** [comment]
I don't know if it works on Android, but I do like this on iOS

```jsx
<PhotoView
            source={{uri: data.data}}
            minimumZoomScale={0.5}
            maximumZoomScale={3}
            androidScaleType="center"
            onLoad={() => console.log("Image loaded!")}
            style={{width: Dimensions.get('window').width, height: Dimensions.get('window').height}} 
            resizeMode={'contain'} />
``

resizeMode should do the work for you

**Comment by yachaka** [comment]
@Crash-- I do the same on iOS but it doesn't works on Android, because Android implementation isn't using react-native `<Image />` component.

**Comment by yachaka** [comment]
@alwx Hello, any updates on this ?

**Comment by Crash--** [comment]
@yachaka Did you try `androidScaleType={"fitCenter"}` seems to do the trick, no? (I can't test on a very large PNG file, but on a big enough one seems ok)

**Comment by yachaka** [comment]
@Crash-- That resolved it ! Thanks, and mea culpa for not reading the docs well enough.
