### ISSUE TITLE
Doesn't work on android with react-native@0.42.3

### ISSUE THREAD

**Issue by TomPradat** [alwx/react-native-photo-view#66]
On android simulator i have an error message : "Unable to resolve module `react-native/Libraries/Components/View/ViewPropTypes`"

I guess this is because of the following import in PhotoView.android.js.
**import ViewPropTypes from 'react-native/Libraries/Components/View/ViewPropTypes';**

**Comment by weijianfeng** [comment]
I have the same problem.

**Comment by th317erd** [comment]
For now use this version in your package.json: "react-native-photo-view": "github:alwx/react-native-photo-view#383b8be6ef2444d74f9eae45359189e6d081de6e"

**Comment by antseburova** [comment]
When I use the recommended above version, the onLoad event on all of the images in my app stops firing. Do you have any idea why that happens?

**Comment by th317erd** [comment]
@antseburova No unfortunately I am not sure why the onLoad event is not firing... however I have ran into this issue before, and so have other people with other RN events, and sometimes clearing all modules, reinstalling them, and rebuilding the binary fresh can fix. You might start there. If that doesn't help you will just have to run it via a debugger and see where the disconnect is.

**Comment by antseburova** [comment]
Okay, thank you!

**Comment by alwx** [comment]
The fix has already been merged.
https://github.com/alwx/react-native-photo-view/pull/82

**Comment by spencewine** [comment]
This still isn't working after this PR was merged today.
