### ISSUE TITLE
Wrong import in react-native 0.42.3

### ISSUE THREAD

**Issue by weijianfeng** [alwx/react-native-photo-view#67]
In 0.42.3, 
ViewPropTypes in  'react-native/Libraries/Components/View/' may change its name to ViewStylePropTypes
but int the file PhotoView.android.js in react-native-photo-view
the following import may cause error when npm start
import ViewPropTypes from 'react-native/Libraries/Components/View/ViewPropTypes'

**Comment by th317erd** [comment]
For now use this version in your package.json: `"react-native-photo-view": "github:alwx/react-native-photo-view#383b8be6ef2444d74f9eae45359189e6d081de6e"`

**Comment by weijianfeng** [comment]
OK，thanks !
