### ISSUE TITLE
White back fill on render

### ISSUE THREAD

**Issue by JperF** [alwx/react-native-photo-view#77]
I am using `react-native-photo-view` to render photos in a swipe friendly  photo view. However sometimes when clicking and rendering the photos the photos are just blank with a white backfill.

<img width="395" alt="screen shot 2017-08-03 at 10 42 42 am" src="https://user-images.githubusercontent.com/4474118/28935187-8cc3893c-7838-11e7-85df-706e0ac2a5a6.png">

This is only happening with the android library you use, iOS work perfectly.

I am not sure if this is something I am doing incorrectly but using the view with multiple images.

```
 {props.photos.map(item => (
    <View key={item.url} style={photoswiperStyles.slide}>
      <TouchableWithoutFeedback onPress={() => props.pressHandle()}>
        <PhotoViewLoader item={item} />
      </TouchableWithoutFeedback>
    </View>
  ))}
```

the problem happens even with a list of one item as well.

**Comment by nihp** [comment]
Did you have any solution for this?

**Comment by JperF** [comment]
@nihp Sorry I don't even remember the context of what I was working on when I posted this. I am going to close this.
