### ISSUE TITLE
Image quality reduced on IOS after applying resizeMode

### ISSUE THREAD

**Issue by DanteXie** [alwx/react-native-photo-view#81]
The library is working perfectly on Android with androidScaleType='fitCenter' applied.

However, I find it hard to achieve the same on IOS with resizeMode='contain' applied. In this case, when I zoom in the image, it's blurred.

My assumption is that image quality suffers from react native image resizing, because if I set resizeMode='cover', image quality gets obviously higher, but of course, still not the original quality if the image is large enough, and the same effect achieved on Android with androidScaleType='fitCenter' applied can not be achieved if resizeMode='cover'.

Haven't found a solution to it yet.

**Comment by zackify** [comment]
Looks like it got fixed in 1.4.0, are you on it?

**Comment by DanteXie** [comment]
Yea, the new version has solved this issue. Great job !!
