### ISSUE TITLE
Cannot see image on iOS after upgrade to v1.4.0

### ISSUE THREAD

**Issue by Sam1301** [alwx/react-native-photo-view#84]
Unfortunately, the image is not visible after upgrading to latest version(1.4.0) and bounds of the photo view are being marked as red.

![edited](https://user-images.githubusercontent.com/14239866/29329529-cc0e0c90-8213-11e7-9030-511d9274f632.jpg)

**Comment by AtticusFetch** [comment]
Can confirm

**Comment by zznull** [comment]
The same thing happens on Android and also when downgrading to 1.3.0.

**Comment by aterribili** [comment]
Any news?

**Comment by opp100** [comment]
Manually link the new library in xcode will solve this problem..

As the picture shown, drag the libRNPhotoView.a to your link binary with Libraries.
<img width="1129" alt="screen shot 2017-08-18 at 10 16 17" src="https://user-images.githubusercontent.com/19526135/29439367-7df9ea76-8400-11e7-95a2-43f134cf27cc.png">

###BUT!!!###
It seems not working when I loading the local image. The remote image looks alright...

**Comment by wolfg1969** [comment]
Can't show the local image. version 1.4.0

**Comment by opp100** [comment]
@wolfg1969 Hey bro, I said it is not working on local image.

**Comment by MataHu** [comment]
Is there anyone who has decided？help~

**Comment by antseburova** [comment]
@opp100 Could you please tell me where you found libRNPhotoView.a? It does not show up anywhere in my project.

**Comment by opp100** [comment]
Hey @antseburova, can you show the local image on this?

**Comment by MataHu** [comment]
Why not drop version to 1.3.x, I went down to 1.3.0 and solved the problem. Just do it

**Comment by opp100** [comment]
Hey @MataHu, because 1.3.x doesn't working probably for RN 0.47.x on android.

**Comment by wolfg1969** [comment]
One big change between 1.3.x and 1.4.0 is this PR #74.

**Comment by antseburova** [comment]
@opp100 No, it works for me with remote images only.
