### ISSUE TITLE
Unresolved Issue

### ISSUE THREAD

**Issue by georgi-kovachev** [alwx/react-native-photo-view#9]
I have this error message
"Unable to resolve module react from /Volumes/Working/Project/mobile/conversations/node_modules/react-native-photo-view/PhotoView.ios.js: Invalid directory /Volumes/node_modules/react"

It seems like it is looking for wrong node_modules directory.

**Comment by georgi-kovachev** [comment]
It works if the index.ios.js is changed into followings inside library (node_modules).

var React = require('react-native');

var {
  View,
  ScrollView,
  Image,
  Component
} = React;

**Comment by alwx** [comment]
@georgi-kovachev can you, please, submit a pull request with this fix?

**Comment by alwx** [comment]
Most probably this bug happens only when using PhotoView with old versions of React Native. The best solution is to update your React Native distribution.
