### ISSUE TITLE
Change background color

### ISSUE THREAD

**Issue by MunazR** [alwx/react-native-photo-view#94]
Is there a way to change the background color of the photo view for iOS? Currently it is black.

**Comment by diegotsi** [comment]
I need to know too. Actually, I'd like to put one loading indicator.How Can i do this?

**Comment by MunazR** [comment]
I created a fork of the repo with the background color set to white if anybody is interested

https://github.com/MunazR/react-native-photo-view

**Comment by CusProjects** [comment]
I think this is a great point, we still need this.

**Comment by alwx** [comment]
Fixed in https://github.com/alwx/react-native-photo-view/commit/848bcdf869fe1c4b06bda502be20f67f4e464eac

**Comment by MunazR** [comment]
Thank you!

**Comment by douglasjunior** [comment]
Why was the color changed to white?

**Comment by lucideer** [comment]
> Fixed

This seems an odd fix. I think the original issue was requesting a configurable background colour, not a global change to a different unconfigurable one.

I came here looking for a way to change it away from black myself, but I do think black is a good **default** value.

**Comment by lucideer** [comment]
For anyone finding this issue:

I've patched my own copy of react-native-photo-view by changing the colour in RNPhotoView.m to `[UIColor clearColor]` - this works best as it allows you to then set any colour on the background of the parent.

**Comment by maciekstosio** [comment]
How is it now? Because I've got black background, but actually I prefer white one...

**Comment by drpiou** [comment]
Still cannot change background color for iOS, Android is working fine...

**Comment by ben-snaize** [comment]
+1  - we need a fix for this.

**Comment by SimonErich** [comment]
+1

**Comment by EsdrasEtrenne** [comment]
It does work

You need to uninstall the app from your simulator and also in package.json install directly from the github repo 

```
  "dependencies": {
    .....other dependencies
    "react-native-photo-view": "github:alwx/react-native-photo-view",
  },
```

then reinstall the app on your simulator `react-native run-ios (or android)`

good to go

**Comment by MaheshNandam** [comment]
Solved By changing:
backgroundColor = [UIColor black] to backgroundColor = [UIColor clearColor];

**Comment by damrem** [comment]
@EsdrasEtrenne 's solution works fine. I did this to "freeze" the version I depend on to today's `master` :
```
"react-native-photo-view": "github:alwx/react-native-photo-view#e28f541",
```
But it would be great to release today's `master` on npm!

**Comment by damrem** [comment]
I did PR #172, for release purpose, I increased minor instead of patch because there were other changes since last npm release (1.5.2).
