### ISSUE TITLE
Unable to resolve viewPropTypes.

### ISSUE THREAD

**Issue by spencewine** [alwx/react-native-photo-view#99]
I saw PR #82  was merged to fix this recently, but it appears to still be broken.  It is throwing the error below when reinstalling the package and running in IOS:

![simulator screen shot sep 5 2017 3 12 42 pm](https://user-images.githubusercontent.com/1612742/30081698-df94f950-924d-11e7-86a2-73dcb53d5c17.png)

Setting the version to: "github:alwx/react-native-photo-view#383b8be6ef2444d74f9eae45359189e6d081de6e" in the package.json as found in #66 fixes the issue, but this issue was closed with the merge of #82 .

**Comment by spencewine** [comment]
issue resolved, realized the version of RN I was using required me to rollback to 1.2.0 here.

**Comment by i8wu** [comment]
thanks for the solution @spencewine , do you know what key features are missing from the older versions? This repo doesn't seem to have a release log.
